### ISSUE TITLE
Screen to migrate public gateway doesn't default to current gateway

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-gateway-desktop#117]
It defaults to `example.relaycorp.cloud`.

**Comment by liliakai** [comment]
You should only see `example.relaycorp.cloud` if the app failed to fetch the current gateway. In testing, I always see  `frankfurt.relaycorp.cloud`. Is it possible the daemon wasn't responding when you saw this? What _should_ be displayed if we get no response from the daemon?

**Comment by gnarea** [comment]
Hmm, good point. The daemon wasn't responding because of #91.

I think defaulting to a valid address (i.e., `frankfurt.relaycorp.cloud`) would be best, if we fail to get a response from the daemon. Wdyt?

BTW, I've just created  #119 so I think this scenario will be even less likely.

**Comment by liliakai** [comment]
See comment on #119. If we exit the app immediately anytime the daemon exits, I'd say this issue is effectively resolved.

**Comment by gnarea** [comment]
Agreed 👍🏾
