### ISSUE TITLE
Electron app doesn't crash when daemon fails to be forked

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-gateway-desktop#119]
#91 didn't cause the app to crash.

This issue may become irrelevant depending on the solution to #91.

**Comment by liliakai** [comment]
#91 is solved in my latest PR, but we should decide what the desired behavior is if the daemon fails to start. This might happen if some other process is already bound to our port, for example. Or if it does start but later exits unexpectedly? The simplest thing is probably to just exit with an error code.

**Comment by gnarea** [comment]
Agreed -- I think we should just exit with an error code for now.

On the daemon side, the process would end with an exit code > 0 if the port is already bound, or if it fails to start for whatever reason.
