### ISSUE TITLE
Courier sync is reported as successful even when it fails

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-gateway-desktop#129]
For example, whilst checking why I'm not seeing the screen in the "UNREGISTERED" status, I started a sync with the courier.

I expected that sync to fail because we're in the `UNREGISTERED` status, but the UI immediately showed the screen you'd see when the sync succeeds. But I can see in the daemon logs that the request was aborted early on because of the current state:

```
{"level":40,"time":1619709970826,"pid":110247,"hostname":"relaybox","msg":"Aborting courier sync because gateway is unregistered"}
```

It should be possible to reproduce this by disconnecting from the courier's WiFi hotspot, but I haven't tried that.

**Comment by liliakai** [comment]
Just pushed a fix to the integration branch. Tested by overwriting the normal close code in `daemon/src/server/control/courierSync.ts`.
