### ISSUE TITLE
Electron's icon is used instead of Awala's on Windows

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-gateway-desktop#133]
![awala-icon](https://user-images.githubusercontent.com/369863/116595943-c5a3f580-a91b-11eb-9ad3-e0a78a680150.png)

**Comment by liliakai** [comment]
Not sure what's wrong here. We definitely pass in the icon path to the window. Maybe Windows is mad because it's not a .ico file?

**Comment by gnarea** [comment]
Ah, yeah, that seems to be the case: https://www.electron.build/icons#windows-nsis

**Comment by gnarea** [comment]
I tried that by manually copying the `src/electron/assets/logo.png` to `build/icon.png` but it didn't work. This was inside `packages/ui`.

**Comment by liliakai** [comment]
I just pushed a change that adds a .ico and configures electron-builder to find it. I'm not set up to test on windows at the moment but I was able to build the windows installer. Before this change it gave a warning about a missing app icon, and after this change, it did not!

**Comment by gnarea** [comment]
Still using the Electron icon :/ 

I'm sure I'm running the latest commit. I've also run `npx lerna run clean` and `npx lerna run build` from the root of the repo before running `npm start` in the UI package, just in case.

**Comment by gnarea** [comment]
I should've mentioned I also experienced this on Linux, but I ignored it because I get the same issue with Slack so I thought it was a problem on my end (but other Electron apps work fine):

![icon-linux](https://user-images.githubusercontent.com/369863/116673368-350cfa00-a99b-11eb-850c-a8207626c352.png)

**Comment by gnarea** [comment]
Checking https://github.com/relaycorp/awala-gateway-desktop/pull/131/commits/efcf863d1bc89277e94294de01b765151e3a5ced, does it work for you on macOS? There are no icons in `build/**`.

**Comment by gnarea** [comment]
Maybe this is the problem, though I don't quite understand how to adapt the suggested solution:

> buildResources = build String - The path to build resources.
>
> Please note — build resources is not packed into the app. If you need to use some files, e.g. as tray icon, please include required files explicitly: `"files": ["**/*", "build/icon.*"]`

https://www.electron.build/configuration/configuration#MetadataDirectories-buildResources

**Comment by liliakai** [comment]
/build is the typescript output directory, so I put the icon in /buildResources, and the config is in package.json (both within in the ui package).
