### ISSUE TITLE
Native dependencies don't work in Electron

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-gateway-desktop#91]
The native dependencies in the daemon package (i.e., gRPC and SQLite) aren't working. I can build the app, but the daemon errors out when forked:

```
/home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/grpc/src/grpc_extension.js:55
    throw error;
    ^

Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v12.0-linux-x64-glibc
Found: [node-v72-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/grpc/src/node/extension_binary/electron-v12.0-linux-x64-glibc/grpc_node.node'
Require stack:
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/grpc/src/grpc_extension.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/grpc/src/client_interceptors.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/grpc/src/client.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/grpc/index.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/@relaycorp/cogrpc/build/main/lib/client.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/@relaycorp/cogrpc/build/main/index.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/build/sync/courierSync/CourierSync.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/build/sync/StatusMonitor.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/build/server/control/connectionStatus.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/build/server/index.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/build/daemon.js
- /home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/build/bin/gateway-daemon.js
    at Object.<anonymous> (/home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gus/repos/awala-gateway-desktop/packages/ui/app/daemon/node_modules/grpc/src/client_interceptors.js:144:12)
    at Module._compile (internal/modules/cjs/loader.js:1078:30) {
  code: 'MODULE_NOT_FOUND'
}
(node:26471) UnhandledPromiseRejectionWarning: ReferenceError: WebSocket is not defined
    at updateToolTip (webpack://ui/./src/electron/main.ts?:93:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I've tried the following but hadn't managed to make things work (I'm sure I'm doing something wrong but can't tell what it is):

- https://www.npmjs.com/package/grpc#about-electron
- https://www.electronjs.org/docs/tutorial/using-native-node-modules#installing-modules-and-rebuilding-for-electron

See #90, for example.

Can you please look into this when you get a chance, Lilia?

**Comment by gnarea** [comment]
I haven't tried this, but I'm wondering whether it'd be best to move away from having the Electron app `fork` the daemon, and instead create a new parent process that `spawns` both the Electron app and the daemon. The new parent process would be responsible for generating the auth token, and it'd pass it to both children via an env var.

That'd make the two processes isolated. However, I don't know if this would make it harder to build/distribute the Electron app.

**Comment by liliakai** [comment]
I got the daemon to work by downloading a prebuilt grpc binary as suggested in https://www.npmjs.com/package/grpc#about-electron. Is that ok, or should I try to get to compile grpc from source?

I haven't seen any errors regarding sqlite so far.

**Comment by gnarea** [comment]
Nice! I must've done something wrong when I tried it. Can you please create a new PR and I'll close #90?

**Comment by liliakai** [comment]
> I haven't tried this, but I'm wondering whether it'd be best to move away from having the Electron app `fork` the daemon, and instead create a new parent process that `spawn`s both the Electron app and the daemon. The new parent process would be responsible for generating the auth token, and it'd pass it to both children via an env var.
> 
> That'd make the two processes isolated. However, I don't know if this would make it harder to build/distribute the Electron app.

By the way, this is already what's happening under the hood. Electron has a main process that handles spawning the daemon, managing the browser window, as well as updating the system tray icon's hover text. That main process could certainly handle the token generation and hand it off to the daemon via a command line argument, or an environment variable instead of waiting for an ipc message. This does simplify the relationship between the processes somewhat.

**Comment by gnarea** [comment]
That's good to know! Though unless the current approach is causing any issues besides maintainability, I'd rather keep it as it is for now. Especially because in the future we might replace `fork`/HTTP with Unix sockets to make the daemon run as different user.
